name: tonosama
favicon: null
layout_spectrum: 0.33809
typography_spectrum: 0.54804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.7230005988385528
purpose: []
