name: tonosama
favicon: null
layout_spectrum: 0.21847
typography_spectrum: 0.47346
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9eb6d8'
    - '#806a53'
    - '#4f8ad8'
    - '#e0e9f8'
    - '#090a05'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
