name: tonosama
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47346
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cbe0fd'
    - '#0a0905'
    - '#c8b48f'
    - '#756857'
    - '#97948f'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
