name: tonosama
favicon: null
layout_spectrum: 0.0054
typography_spectrum: 0.47346
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#292a35'
    - '#3a3a3c'
    - '#58575d'
    - '#6f6d6e'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
