name: tonosama
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47346
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0b13'
    - '#1d2124'
    - '#42433b'
    - '#535d55'
    - '#757d6e'
  brandStrength: 0.6875
  lightness: 0.4375
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
