analytics: {}
color:
  brandColors:
    - '#9eb6d8'
    - '#806a53'
    - '#4f8ad8'
    - '#e0e9f8'
    - '#090a05'
  brandStrength: 0.5
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0
name: tonosama
opengraph: {}
purpose: []
typography_spectrum: 0.41554
