analytics: {}
color:
  brandColors:
    - '#A8B8D0'
    - '#081828'
    - '#687898'
    - '#4078C0'
    - '#78A8E0'
  brandStrength: 0.5
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.231981
name: 'tonosama '
opengraph: {}
purpose: []
typography_spectrum: 0.41554
