name: tonosama
favicon: null
layout_spectrum: 0.05489
typography_spectrum: 0.47346
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6d66ff'
    - '#38009d'
    - '#200058'
    - '#5b43f3'
    - '#5117e1'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
