name: tonosama
favicon: null
layout_spectrum: 0
typography_spectrum: 0.47346
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7b9b8'
    - '#635646'
    - '#918e87'
    - '#24311f'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
