name: tonosama
favicon: null
layout_spectrum: 0.02293
typography_spectrum: 0.43821
title: tonosama
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#002300'
    - '#4b9100'
    - '#a6aeff'
    - '#f6d900'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
