name: tonosama
favicon: null
layout_spectrum: 0.13411
typography_spectrum: 0.56011
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bed3ee'
    - '#6998c4'
    - '#000000'
    - '#282b18'
    - '#645421'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
