name: tonosama
favicon: null
layout_spectrum: 0.53362
typography_spectrum: 0.54804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeff00'
    - '#fffeff'
    - '#236500'
    - '#a8c400'
    - '#868d93'
  brandStrength: 0.9375
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.7230005988385528
purpose: []
