layout_spectrum: 0.231981
typography_spectrum: 0.421573679195717
color:
  brandColors:
    - '#A8B8D0'
    - '#081828'
    - '#687898'
    - '#4078C0'
    - '#78A8E0'
  brandStrength: 0.5
  lightness: 0.375
  rhythmicContrast: 0.5
  saturation: 0.5
analytics: {}
cta: {}
name: 'tonosama '
opengraph: {}
purpose: []
