name: tonosama
favicon: null
layout_spectrum: 0.53362
typography_spectrum: 0.54804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bed3ee'
    - '#6998c4'
    - '#000000'
    - '#282b18'
    - '#645421'
  brandStrength: 0.4375
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
